export default {     
  FORM : {
    NAME:"FormModule",
    // validation
    SET_ERRORS:"SET_ERRORS",
    GET_ERRORS:"GET_ERRORS",
    // state
    STATE_CREATE: "STATE_CREATE",
    STATE_EDIT: "STATE_EDIT",
    GET_STATE:"GET_STATE",
    SET_STATE:"SET_STATE",
    // form action
    EDIT_FORM:"EDIT_FORM",
    CREATE_FORM:"CREATE_FORM",
    RESET_FORM:"RESET_FORM",
    // project manipulation
    GET_PROJECT: "GET_PROJECT",
    SET_PROJECT:"SET_PROJECT",
    CREATE_PROJECT: "CREATE_PROJECT",
    UPDATE_PROJECT: "UPDATE_PROJECT",
    DELETE_PROJECT: "DELETE_PROJECT"
  },
  PROJECT: {
    NAME:"projectModule",
    FETCH_PROJECT: "FETCH_PROJECT",
    GET_PROJECTS: "GET_PROJECTS",
    FETCH_PROJECTS: "FETCH_PROJECTS",
    SET_PROJECTS:"SET_PROJECTS",
    SET_PROJECT_AT:"SET_PROJECT_AT",
    REMOVE_PROJECT_AT:"REMOVE_PROJECT_AT",
    PUSH_PROJECT:"PUSH_PROJECT"
  },
  MESSAGE: {
    NAME:"messageModule",
    SET_MESSAGE:"SET_MESSAGE",
    GET_MESSAGE:"GET_MESSAGE",
    SET_VISIBLE:"SET_VISIBLE"
  }
};